#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:10:00      # hh:mm:ss for the job
#SBATCH --constraint="scratch"

module load openmpi-5.0_beta/5.0.0rc9
echo "job is starting ppn=2, process cnt per node=1, node=1 on `hostname`"
srun --mpi=pmi2 -n 2 ./pgm_fixed ++ppn 8 +pemap 1-8 +commap 10
